
PIX=\
mulle-sde-add.png \
mulle-sde-cmakelists.png \
mulle-sde-craft.png \
mulle-sde-dependency.png \
mulle-sde-environment.png \
mulle-sde-extension.png \
mulle-sde-extension-fs.png \
mulle-sde-library.png \
mulle-sde-list.png \
mulle-sde-linkorder.png \
mulle-sde-log.png \
mulle-sde-patternfile.png \
mulle-sde-monitor.png \
mulle-sde-overview.png \
mulle-sde-reflect.png \
mulle-sde-subproject.png \
mulle-sde-status.png \
mulle-sde-tool.png \
reflect.png \
craft.png

%.png: %.dot
	dot -Tpng -o $*.png $<


all: $(PIX)
