
PIX=\
mulle-sde-add.svg \
mulle-sde-cmakelists.svg \
mulle-sde-craft.svg \
mulle-sde-dependency.svg \
mulle-sde-environment.svg \
mulle-sde-extension.svg \
mulle-sde-extension-fs.svg \
mulle-sde-library.svg \
mulle-sde-list.svg \
mulle-sde-linkorder.svg \
mulle-sde-log.svg \
mulle-sde-patternfile.svg \
mulle-sde-monitor.svg \
mulle-sde-overview.svg \
mulle-sde-reflect.svg \
mulle-sde-subproject.svg \
mulle-sde-status.svg \
mulle-sde-tool.svg \
reflect.svg \
craft.svg

%.svg: %.dot
	dot -Tsvg -o $*.svg $<


all: $(PIX)
