#! /usr/bin/env bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION=0.17.2
MULLE_EXECUTABLE_BASHFUNCTIONS="1"


#
# This is the main user interface to mulle-sde
# sorta like git
#

trap_fail()
{
   exit 1
}


print_commands()
{
   local show_all="${1:-NO}"

   HIDDEN_COMMANDS="\
   callback       : manage callbacks
   fetch          : fetch the sourcetree
   find           : find files that match patternfiles
   init-and-enter : create a new project then immediately start a subshell
   libexec-dir    : print path to mulle-sde libexec
   mark           : add a mark to a dependency or library
   match          : experiment with patternfiles
   patternfile    : manage patternfiles
   task           : manage tasks
   test           : run tests using mulle-test
   uname          : mulle-sdes simplified uname(1)
   unmark         : add a mark to a dependency or library"

   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      SHOWN_COMMANDS="\
   extension      : show available language and buildtool extensions
   init           : create a new project"

      HIDDEN_COMMANDS="\
   clean          : clean various parts of the project
   craft          : build the project and dependencies using mulle-craft
   dependency     : manage third party components (like GitHub projects)
   environment    : manage environment variables (project settings)
   clean          : clean various parts of the project
   craft          : build the project using mulle-craft
   dependency     : manage third party components (like GitHub projects)
   environment    : manage environment variables (project settings)
   extension      : show available language and buildtool extensions
   init           : create a new project
   library        : manage second party (OS) libraries (like pthread)
   monitor        : monitor project files, run update and build
   subproject     : manage local subprojects
   update         : update project makefiles"
   else
      SHOWN_COMMANDS="\
   buildorder     : show buildorder of dependencies
   clean          : clean various parts of the project
   craft          : build the project using mulle-craft
   dependency     : manage third party components (like GitHub projects)
   environment    : manage environment variables (project settings)
   extension      : show available language and buildtool extensions
   init           : create a new project
   library        : manage second party (OS) libraries (like pthread)
   monitor        : monitor project files, run update and build
   subproject     : manage local subprojects
   update         : update project makefiles"
   fi

   echo "${SHOWN_COMMANDS}" | sort

   if [ "${show_all}" != "NO" ]
   then
      echo "${HIDDEN_COMMANDS}" | sort
   fi
}


print_flags()
{
   local delimiter

   delimiter="          : "

   echo "   -e   ${delimiter}bypass mulle-env check"
   echo "   -f   ${delimiter}force operation"
   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      echo "   --style <val>  : see \`mulle-env help\` for style description"
   fi

   options_technical_flags_usage "${delimiter}"
}


_usage()
{
   local verbose="${1:-NO}"

   cat <<EOF
Usage:
   ${MULLE_USAGE_NAME} [flags] [command] [options]

   The commandline IDE.

EOF
   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      cat <<EOF
   Create a new project with \`mulle-sde init\` or enter an existing one with
   \`mulle-sde <directory>\`.

EOF
   else
      cat <<EOF
   To start development run \`mulle-sde monitor\` in this shell and edit your
   source files in 'src' in another shell. Or periodically run
   \`mulle-sde update\` followed by \`mulle-sde craft\` to build.

EOF
   fi

   cat <<EOF
Flags:
EOF
   print_flags  | sort


   cat <<EOF

Commands:
EOF

   print_commands "${verbose}" | sort

   if [ "${verbose}" = "NO" ]
   then
      cat <<EOF
      (use mulle-sde -v help to show more commands)
EOF
   fi

   cat <<EOF

   Options are command specific. Use ${MULLE_USAGE_NAME} <command> -h for help.
EOF

   exit 1
}


usage()
{
   _usage "$@" >&2
   exit 1
}


determine_project_dir()
{
   local current

   current="`pwd -P`"

   while [ "${current}" != "/" ]
   do
      if [ -d "${current}/.mulle-sde" ]
      then
         exekutor echo "${current}"
         return
      fi

      if [ -z "${MULLE_PATH_SH}" ]
      then
         . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh" || return 1
      fi
      if [ -z "${MULLE_FILE_SH}" ]
      then
         . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh" || return 1
      fi

      current="`fast_dirname "${current}"`"
   done
   return 1
}


cd_virtual_root()
{
   local cmd="$1"
   local subenvcheck="${2:-YES}"

   if [ "${subenvcheck}" = "YES" ]
   then
      case "${MULLE_SHELL_MODE}" in
         *SUBENV*)
            fail "You can not run \`mulle-sde ${cmd}\` inside a sub-environment"
         ;;
      esac
   fi

   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      fail "To run ${MULLE_EXECUTABLE_NAME} outside of mulle-env, pass the -e flag"
   fi
   exekutor cd "${MULLE_VIRTUAL_ROOT}" || exit 1

}


main()
{
   local MULLE_FLAG_MAGNUM_FORCE="NO"

   # technical flags
   local MULLE_TRACE
   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
   local MULLE_FLAG_LOG_LOCAL="NO"
   local MULLE_FLAG_LOG_DEBUG="NO"
   local MULLE_FLAG_LOG_EXEKUTOR="NO"
   local MULLE_FLAG_LOG_FLUFF="NO"
   local MULLE_FLAG_LOG_SCRIPTS="NO"
   local MULLE_FLAG_LOG_SETTINGS="NO"
   local MULLE_FLAG_LOG_VERBOSE="NO"
   local MULLE_FLAG_LOG_MERGE="NO"
   local MULLE_TRACE_POSTPONE="NO"

   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help|help)
            usage "${MULLE_TRACE}"
         ;;

         -e)
            FLAG_OUTSIDE_ENV="YES"
         ;;

         -f|--force)
            MULLE_FLAG_MAGNUM_FORCE="YES"
            MULLE_FWD_FLAGS="`concat "${MULLE_FWD_FLAGS}" "$1" `"
         ;;

         --git-terminal-prompt)
            [ $# -eq 1 ] && fail "missing argument to \"$1\""
            MULLE_FWD_FLAGS="`concat "${MULLE_FWD_FLAGS}" "$1" `"
            shift

            GIT_TERMINAL_PROMPT="$1"
            export GIT_TERMINAL_PROMPT

            MULLE_FWD_FLAGS="`concat "${MULLE_FWD_FLAGS}" "$1" `"
         ;;

         --style)
            [ $# -eq 1 ] && fail "missing argument to \"$1\""
            MULLE_ENV_FLAGS="`concat "${MULLE_ENV_FLAGS}" "$1" `"
            shift

            MULLE_ENV_FLAGS="`concat "${MULLE_ENV_FLAGS}" "$1" `"
         ;;

         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         --no-search)
            MULLE_ENV_FLAGS="`concat "${MULLE_ENV_FLAGS}" --no-search`"
         ;;

         -*)
            log_error "Unknown option \"$1\""
            usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   MULLE_ENV="${MULLE_ENV:-`command -v mulle-env`}"
   [ -z "${MULLE_ENV}" ] && fail "mulle-env not in PATH"

   if [ "${FLAG_OUTSIDE_ENV}" = "YES" ]
   then
      MULLE_VIRTUAL_ROOT="`pwd -P`"
      [ "${MULLE_VIRTUAL_ROOT}" = "/" ] && fail "MULLE_VIRTUAL_ROOT can't be /"
      export MULLE_VIRTUAL_ROOT
   else
      #
      # a "convenient" ? shortcut to do projects w/o having to enter
      # a subshell. Starts a subshell every time though....
      #
      if [ -z "${MULLE_VIRTUAL_ROOT}" ]
      then
         local cmd="$1"

         # commands where we want to start a subshell

         case "${cmd}" in
            buildorder|callback|clean|craft|dependency|environment|fetch|find|\
library|mark|match|monitor|patternfile|subproject|task|template|tool|unmark|\
update)
               cd "`determine_project_dir`" || exit 1

               local cmdline

               cmdline="mulle-sde"
               cmdline="${cmdline} ${MULLE_TECHNICAL_FLAGS}"
               cmdline="${cmdline} ${MULLE_FWD_FLAGS}"

               while [ $# -ne 0 ]
               do
                  cmdline="${cmdline} '$1'"
                  shift
               done

               log_fluff "Run command in subshell: \"${cmdline}\""
               exekutor exec "${MULLE_ENV}" ${MULLE_ENV_FLAGS} -c "${cmdline}"
            ;;

            bash-completion|extension|init|init-and-enter|reinit|uname|version\
libexec-dir|library-path|project-dir)
            ;;

            "")
               exekutor exec "${MULLE_ENV}" ${MULLE_ENV_FLAGS} 
            ;;

            *)
               if [ $# -eq 1 ] && [ -d "$1" ]
               then
                  exekutor exec "${MULLE_ENV}" ${MULLE_ENV_FLAGS} "$@"
               fi

               usage "${MULLE_TRACE}"
            ;;
         esac
      fi
   fi
   
   options_setup_trace "${MULLE_TRACE}"

   local cmd

   cmd="$1"
   [ $# -ne 0 ] && shift

   MULLE_SDE_DIR="${MULLE_VIRTUAL_ROOT}/.mulle-sde"
   MULLE_SDE_ETC_DIR="${MULLE_SDE_ETC_DIR:-${MULLE_SDE_DIR}/etc}"
   MULLE_EXECUTABLE_OPTIONS="$@"

   MULLE_SOURCETREE="${MULLE_SOURCETREE:-`command -v mulle-sourcetree`}"
   [ -z "${MULLE_SOURCETREE}" ] && fail "mulle-sourcetree not in PATH"

   MULLE_MONITOR="${MULLE_MONITOR:-`command -v mulle-monitor`}"
   [ -z "${MULLE_MONITOR}" ] && fail "mulle-monitor not in PATH"

   MULLE_CRAFT="${MULLE_CRAFT:-`command -v mulle-craft`}"
   [ -z "${MULLE_CRAFT}" ] && fail "mulle-craft not in PATH"

   MULLE_MATCH="${MULLE_MATCH:-`command -v mulle-match`}"
   [ -z "${MULLE_MATCH}" ] && fail "mulle-match not in PATH"

   case "${cmd}" in
      bash-completion)
         echo "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-bash-completion.sh"
      ;;

      buildorder)
         cd_virtual_root "${cmd}"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_SOURCETREE}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_SOURCETREE_FLAGS} "${cmd}" "$@"
      ;;

      callback|task)
         cd_virtual_root "${cmd}"

         MULLE_MONITOR_DIR="${MULLE_SDE_MONITOR_DIR:-${MULLE_SDE_DIR}}" \
         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_MONITOR}" ${MULLE_TECHNICAL_FLAGS} \
                  ${MULLE_MONITOR_FLAGS} "${cmd}" "$@"
      ;;

      clean)
         cd_virtual_root "${cmd}"

         # shellcheck source=src/mulle-sde-clean.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-clean.sh"

         exekutor cd "${MULLE_VIRTUAL_ROOT}" || exit 1
         sde_clean_main "$@"
      ;;

      #
      # forward stuff to mulle-craft verbatim
      #
      craft)
         cd_virtual_root "${cmd}"

         # shellcheck source=src/mulle-sde-craft.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-craft.sh"
         sde_craft_main "$@"
      ;;

      dependency)
         cd_virtual_root "${cmd}" "NO"

         # shellcheck source=src/mulle-sde-dependency.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-dependency.sh"

         sde_dependency_main "$@"
      ;;

      environment)
         cd_virtual_root "${cmd}" "NO"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_ENV}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_ENV_FLAGS} "${cmd}" "$@"
      ;;

      extension)
         # shellcheck source=src/mulle-sde-extension.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-extension.sh"

         sde_extension_main "$@"
      ;;

      fetch)
         cd_virtual_root "${cmd}"

         # shellcheck source=src/mulle-sde-fetch.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-fetch.sh"

         sde_fetch_main "$@"
      ;;

      find)
         cd_virtual_root "${cmd}" "NO"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_MATCH}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_MATCH_FLAGS} "find" \
                          --format "%t/%c: %f\\n" "$@"
      ;;

      "")
         usage "${MULLE_TRACE}"
      ;;

      init)
         # shellcheck source=src/mulle-sde-init.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-init.sh"

         sde_init_main "$@"
      ;;

      init-and-enter)
         # shellcheck source=src/mulle-sde-init.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-init.sh"

         # interactive shell, dont set usage
         sde_init_main --no-blurb "$@" &&
            exekutor "${MULLE_ENV}" ${MULLE_TECHNICAL_FLAGS} ${MULLE_ENV_FLAGS}
      ;;

      library)
         cd_virtual_root "${cmd}" "NO"

         # shellcheck source=src/mulle-sde-library.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-library.sh"

         sde_library_main "$@"
      ;;

      libexec-dir|library-path)
         exekutor echo "${MULLE_SDE_LIBEXEC_DIR}"
      ;;

      mark|unmark)
         cd_virtual_root "${cmd}" "NO"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_SOURCETREE}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_SOURCETREE_FLAGS} "${cmd}" "$@"
      ;;

      match|patternfile)
         cd_virtual_root "${cmd}" "NO"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_MATCH}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_MATCH_FLAGS} "${cmd}" "$@"
      ;;

      monitor)
         cd_virtual_root "${cmd}"

         # shellcheck source=src/mulle-sde-monitor.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-monitor.sh"

         sde_monitor_main "$@"
      ;;

      project-dir)
         determine_project_dir
      ;;

      reinit)
         if [ "${MULLE_FLAG_MAGNUM_FORCE}" != "YES" ]
         then
            log_error "You must run ${C_RESET_BOLD}reinit${C_ERROR} with the -f flag, as it is destructive!"
#
# reinit -f clobbers! so demo and project are off by default
#
            log_info "  Additionally specify option --allow-project if you want to reinit project files"
            log_info "  Additionally specify option --allow-demo if you want to reinit demo files"
            exit 1
         fi

         # shellcheck source=src/mulle-sde-init.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-init.sh"

         sde_init_main --reinit "$@"
      ;;

      style)
         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_ENV}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_ENV_FLAGS} "${cmd}" "$@"
      ;;

      subproject)
         cd_virtual_root "${cmd}" "NO"

         # shellcheck source=src/mulle-sde-subproject.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-subproject.sh"

         sde_subproject_main "$@"
      ;;

      template)
         cd_virtual_root "${cmd}"

         # shellcheck source=src/mulle-sde-tool.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-template.sh"

         sde_template_main "$@"
      ;;

      tool)
         cd_virtual_root "${cmd}"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_ENV}" ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_ENV_FLAGS} "${cmd}" "$@"
      ;;

      update)
         cd_virtual_root "${cmd}" "NO"

         # shellcheck source=src/mulle-sde-update.sh
         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-update.sh"

         sde_update_main "$@"
      ;;

      uname)
         exekutor echo "${MULLE_UNAME}"
      ;;

      version)
         exekutor echo "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      *)
         log_error "Unknown command \"${cmd}\""
         usage "${MULLE_TRACE}"
      ;;
   esac
}


########
###
### INIT
###
_init()
{
   #
   # minimal setup exit
   #
   if [ "$1" = "version" ]
   then
      echo "${MULLE_EXECUTABLE_VERSION}"
      exit 0
   fi

   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
      then
         if [ -z "`command -v "${executablepath}"`" ]
         then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
         else
            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
         fi
         exit 1
      fi
   fi

      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"

   local _libexec_dir

   _get_libexec_dir "$0" "mulle-sde" "mulle-sde-craft.sh"

   MULLE_SDE_LIBEXEC_DIR="${_libexec_dir}"

   #
   # minimal setup exit
   #
   case "$1" in
      "libexec-dir"|"library-path")
         echo "${MULLE_SDE_LIBEXEC_DIR}"
         exit 0
      ;;
   esac

   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   trap trap_fail INT
   set -o pipefail
   shopt -s extglob
}
###
### INIT
###
########



_init "$@" # needs params
main "$@"
