#! /usr/bin/env bash
#
#   Copyright (c) 2015 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
MULLE_SDE_VERSION=0.2.0

MULLE_EXECUTABLE_FUNCTIONS_MIN="3.9"
MULLE_EXECUTABLE_FUNCTIONS_MAX="4"


usage()
{
    cat <<EOF >&2
Usage:
   ${MULLE_EXECUTABLE} [options] [path|url] [mulle-bootstrap-flags]

   Create a virtual environment for project in directory.
   If the directory at path does not exist and the path looks like an url,
   ${MULLE_EXECUTABLE} will attempt to git clone the project from that url.

Options:
   -m        : set CPPFLAGS and LDFLAGS in environment for make
   -d <dir>  : specify different directory, than the one taken from the url
   -ni       : don't inherit PATH, LD_LIBRARY_PATH and related environment
EOF
  exit 1
}


run_shell()
{
   #
   # could pimp this up with CPPFLAGS and LDFLAGS too
   # but do I want this ?
   #
   local options

   options="run"
   if [ "${OPTION_MAKE_FLAGS}" = "YES" ]
   then
      options="${options} make"
   fi

   local pathoptions

   if [ "${OPTION_INHERIT}" = "NO" ]
   then
      pathoptions="-ni"
   fi

   local path
   local name
   local env_string
   local cmd_string
   local cmd_options

   if [ -d ".bootstrap" -o -d ".bootstrap.local" ]
   then
      path="`mulle-bootstrap master-path`" || return 1

      env_string="`mulle-bootstrap paths ${pathoptions} -m -1 -q "'" ${options}`" || return 1
   else
      path="`pwd -P`"
   fi

   name="`basename -- "${path}"`"
   cmd_string="${SHELL:-/usr/bin/env bash}"

   local prompt_string
   local initfile

   #
   # because some environment strings like
   # DYLD_LIBRARY_PATH are stripped off by dyld (I guess)
   # put everything in an init file if possible
   #
   case "${cmd_string}" in
      *bash|*dash)
         initfile="`mktemp .environment.XXXXXXX`" || exit 1
         echo "${env_string}" > "${initfile}"
         echo "[ -f \".mulle-sde-environment.sh\" ] && . \".mulle-sde-environment.sh\"" >> "${initfile}"
         echo "( sleep 1 ; rm \"${initfile}\" 2> /dev/null ) &" >> "${initfile}"
         if [ ! -z "${targetdirectory}" ]
         then
            echo "cd \"${targetdirectory}\"" >> "${initfile}"
         fi
         cmd_options="--rcfile '${initfile}'"
      ;;
   esac

   case "${cmd_string}" in
      *bash|*dash)
         case "${PS1}" in
            *\\h[*)
               prompt_string="PS1='${PS1}'"
            ;;

            *\\h*)
               prompt_string="PS1='$(sed "s/\\\\h/\\\\h\\[${name}\\]/" <<< "${PS1}")"
            ;;

            *)
               prompt_string="PS1='\u@\h[${name}] \W$ '"
            ;;
         esac
      ;;
   esac

   eval_exekutor "MULLE_SDE_VIRTUAL_ROOT='${path}'" \
                 "${env_string}" \
                 "${prompt_string}" \
                  "'${cmd_string}'" \
                  "${cmd_options}" \
                  "$@"

  if [ -f "${initfile}" ]
  then
      rm "${initfile}"
  fi
}


main()
{
   local OPTION_MAKE_FLAGS="NO"
   local OPTION_DIRECTORY
   local OPTION_INHERIT="YES"
   local OPTION_BOOTSTRAP="YES"

   while [ $# -ne 0 ]
   do
      if core_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help)
            usage
         ;;

         -m|--make)
            OPTION_MAKE_FLAGS="YES"
         ;;

         -d|--directory)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            OPTION_DIRECTORY="$1"
         ;;

         -ni|--no-inherit)
            OPTION_INHERIT="NO"
         ;;

         -nb|--no-bootstrap)
            OPTION_BOOTSTRAP="NO"
         ;;

         # argument gitflags
         -*)
            fail "unknown option $1"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   core_setup_trace "${MULLE_TRACE}"
   export MULLE_TRACE

   #
   # lets do this for now
   #
   if [ ! -z "${MULLE_SDE_VIRTUAL_ROOT}" ]
   then
      fail "You are already in the mulle-bootstrap virtual environment \"${MULLE_SDE_VIRTUAL_ROOT}\". Environments don't stack."
   fi

   local arg
   local directory
   local url
   local calldirectory

   calldirectory="`pwd -P`"

   arg="$1"
   [ $# -ne 0 ] && shift

   if [ ! -z "${OPTION_DIRECTORY}" ]
   then
      directory="${OPTION_DIRECTORY}"
   else
      if [ -z "${arg}" ]
      then
         directory="${calldirectory}"

         local found

         found="NO"
         # look for .mulle-sde-environment.sh going up to root, if we
         # find one, we latch onto it
         while [ "${directory}" != "." ]
         do
            if [ -f "${directory}/.mulle-sde-environment.sh" ]
            then
               found="YES"
               break
            fi
            directory="`dirname -- "${directory}"`"
         done

         if [ "${found}" = "NO" ]
         then
            directory="${calldirectory}"
         fi
      else
         if [ -d "${arg}" ]
         then
            directory="$arg"
         else
            directory="`basename -- "${arg}"`" || return 1
         fi
      fi
   fi

   if [ ! -d "${directory}/.bootstrap" -a ! -d "${directory}/.bootstrap.local" ]
   then
      if [ -z "`command -v git`" ]
      then
         fail "git not installed, can't clone stuff for you"
      fi

      case "${arg}" in
         "")
            url=""
         ;;

         *:*)
            url="${arg}"
         ;;

         *)
            url="https://github.com/${arg}"
         ;;
      esac

      if [ ! -z "${url}" ]
      then
         log_verbose "Cloning from URL \"${arg}\" into \"${directory}\"..."
         git clone "${url}" "${directory}" || return 1
      else
         if [ ! -d "${directory}" ]
         then
            fail "${directory} does not exist"
         fi
      fi
   fi

   if [ "${OPTION_BOOTSTRAP}" = "YES" ] && \
      [ -d "${directory}/.bootstrap" -o  -d "${directory}/.bootstrap.local" ] && \
      [ ! -d "${directory}/.bootstrap.auto" ]
   then
      local exepath

      # weird, but if there is a mulle-bootstrap folder in the top directory
      # you can't run mulle-bootstrap via bash so resolve before
      exepath="`command -v mulle-bootstrap`"
      log_fluff "Running mulle-bootstrap in \"${directory}\"..."
      ( cd "${directory}" ; run_shell "${exepath}" )
   fi

   log_fluff "Run shell in \"${calldirectory}\"..."

   if [ "${targetdirectory}" != "${calldirectory}" ]
   then
      targetdirectory="${calldirectory}"
   fi

   ( cd "${directory}" ; run_shell "$@" )
   return $?
}



_init()
{
   libexecpath="`mulle-bootstrap library-path 2> /dev/null`"
   if [ -z "${libexecpath}" ]
   then
      echo "Fatal Error: Could not find mulle-bootstrap library for ${MULLE_EXECUTABLE}" >&2
      exit 1
   fi

   . ${libexecpath}/mulle-bootstrap-logging.sh || internal_fail "mulle-bootstrap-logging.sh not found"
   . ${libexecpath}/mulle-bootstrap-functions.sh || internal_fail "mulle-bootstrap-functions.sh not found"
   . ${libexecpath}/mulle-bootstrap-core-options.sh || internal_fail "mulle-bootstrap-core-options.sh not found"
}


MULLE_EXECUTABLE="`basename -- "$0"`"
MULLE_ARGUMENTS="$@"
MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE}"
MULLE_EXECUTABLE_PID="$$"


set -o pipefail

_init "$@" # needs params


#
# combine all coverage files into one and sort -u it
#

main "$@"

