#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sde()
{
   (
      MULLE_EXECUTABLE="${MULLE_SDE}"
      MULLE_SDE_LIBEXEC_DIR="`${MULLE_SDE} libexec-dir`"

      . "${MULLE_SDE}" ${MULLE_SDE_FLAGS} "$@"
   )
}


assert_no_dead_owner_warning()
{
   case "$1" in
      *'broke dead-owner lock'*)
         fail "Unexpected stale lock recovery warning in output:
$1"
      ;;
   esac
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory
   local output
   local rc

   r_make_tmp_directory
   directory="${RVAL:-/tmp/build}"

   run_mulle_sde -s init \
                    -d "${directory}" \
                    -m mulle-sde/c-developer \
                    executable \
   || fail "init failed"

   (
      cd "${directory}" || exit 1

      run_mulle_sde -s craft || fail "initial craft failed"
      [ ! -d ".mulle/var/craft.lock" ] || fail "craft lock leaked after successful craft"

      echo 'this will not compile' >> src/main.c

      output="`run_mulle_sde -v craft 2>&1`"
      rc=$?
      [ ${rc} -ne 0 ] || fail "craft with broken source unexpectedly succeeded"
      assert_no_dead_owner_warning "${output}"
      [ ! -d ".mulle/var/craft.lock" ] || fail "craft lock leaked after failed craft"

      output="`run_mulle_sde -v craft 2>&1`"
      rc=$?
      [ ${rc} -ne 0 ] || fail "second failed craft unexpectedly succeeded"
      assert_no_dead_owner_warning "${output}"
      [ ! -d ".mulle/var/craft.lock" ] || fail "craft lock leaked after repeated failed craft"
   ) || exit 1

   log_info "----- ALL PASSED -----"

   cd ..
   chmod -R u+w "${directory}" 2>/dev/null
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SDE="${MULLE_SDE:-${PWD}/../../mulle-sde}"
}


init "$@"
main "$@"
