#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sde()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SDE} ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      MULLE_EXECUTABLE="${MULLE_SDE}"
      MULLE_SDE_LIBEXEC_DIR="`${MULLE_SDE} libexec-dir`"

      . "${MULLE_SDE}" ${MULLE_SDE_FLAGS} "$@"
   )
}


expect_line()
{
   local pattern="$1"
   local text="$2"

   if ! printf "%s\n" "${text}" | grep -q "${pattern}"
   then
      fail "Expected pattern \"${pattern}\" not found in output:
${text}"
   fi
}


run_case()
(
   local projecttype="$1"
   local projectdir="$2"

   run_mulle_sde init \
                 -d "${projectdir}" \
                 -m mulle-sde/c-developer \
                 "${projecttype}" \
   || fail "${projecttype} init failed"

   (
      cd "${projectdir}" || fail "no project dir found"

      run_mulle_sde test init || fail "${projecttype} test init failed"
      (
         cd test || fail "no test dir found"

         if [ -f '10-first/hello.stdout' ]
         then
            case "${projecttype}" in
               'library')
                  redirect_exekutor '10-first/hello.stdout' echo 'VfL Bochum <missing number, please fix>'
               ;;

               *)
                  redirect_exekutor '10-first/hello.stdout' echo 'VfL Bochum 1848'
               ;;
            esac
         fi

         run_mulle_sde test clean || fail "${projecttype} test clean in test dir failed"
         run_mulle_sde test craft || fail "${projecttype} test craft in test dir failed"
         run_mulle_sde test run   || fail "${projecttype} test run  in test dir failed"
      ) || exit 1
   )
)


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   directory="${directory:-/tmp/build}"

   run_case executable "${directory}/executable" || exit 1

   log_verbose "----- #1 PASSED -----"

   run_case library "${directory}/library" || exit 1

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"

   cd ..
   chmod -R u+w "${directory}" 2>/dev/null
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SDE="${MULLE_SDE:-${PWD}/../../mulle-sde}"
}


init "$@"
main "$@"
