#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sde()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SDE} ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      MULLE_EXECUTABLE="${MULLE_SDE}"
      MULLE_SDE_LIBEXEC_DIR="`${MULLE_SDE} libexec-dir`"

      . "${MULLE_SDE}" ${MULLE_SDE_FLAGS} "$@"
   )
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory
   local output

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   directory="${directory:-/tmp/build}"

   run_mulle_sde -s init \
                    -d "${directory}" \
                    -m mulle-sde/c-developer \
                    executable \
   || fail "init failed"

    (
       cd "${directory}" || exit 1
       output="`run_mulle_sde config list 2>&1`" || fail "config list failed"

      case "${output}" in
         *"syntax error near unexpected token"*)
            fail "config list output contains shell parse error:
${output}"
         ;;
      esac

       case "${output}" in
          *"= config"*) ;;
          *)
             fail "config list output missing default config line:
${output}"
          ;;
       esac

       mkdir_if_missing ".mulle/etc/sourcetree" || fail "mkdir sourcetree failed"
       exekutor touch ".mulle/etc/sourcetree/config" || fail "touch config failed"
       exekutor touch ".mulle/etc/sourcetree/x11" || fail "touch x11 failed"
       exekutor touch ".mulle/etc/sourcetree/wayland" || fail "touch wayland failed"
       exekutor touch ".mulle/etc/sourcetree/macos" || fail "touch macos failed"

       output="`run_mulle_sde config show 2>&1`" || fail "config show failed"

       local projectline
       projectline="`printf "%s\n" "${output}" \
                    | grep '^MULLE_SOURCETREE_CONFIG_NAME=' \
                    | head -n 1`"

       [ -z "${projectline}" ] && fail "config show output missing project line:
${output}"

       case "${projectline}" in
          *"config"*) ;;
          *) fail "config show project line missing \"config\": ${projectline}" ;;
       esac

       case "${projectline}" in
          *"x11"*) ;;
          *) fail "config show project line missing \"x11\": ${projectline}" ;;
       esac

       case "${projectline}" in
          *"wayland"*) ;;
          *) fail "config show project line missing \"wayland\": ${projectline}" ;;
       esac

       case "${projectline}" in
          *"macos"*) ;;
          *) fail "config show project line missing \"macos\": ${projectline}" ;;
       esac

       case "${projectline}" in
          *"default"*)
             fail "config show project line should not synthesize \"default\": ${projectline}"
          ;;
       esac
    ) || exit 1

   log_info "----- ALL PASSED -----"

   cd ..
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SDE="${MULLE_SDE:-${PWD}/../../mulle-sde}"
}


init "$@"
main "$@"
