#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sde()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SDE} ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      MULLE_EXECUTABLE="${MULLE_SDE}"
      MULLE_SDE_LIBEXEC_DIR="`${MULLE_SDE} libexec-dir`"

      . "${MULLE_SDE}" ${MULLE_SDE_FLAGS} "$@"
   )
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory
   local output

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   directory="${directory:-/tmp/build}"

   run_mulle_sde -s init \
                    -d "${directory}" \
                    -m mulle-sde/c-developer \
                    executable \
   || fail "init failed"

   (
      cd "${directory}" || exit 1
      output="`run_mulle_sde config list 2>&1`" || fail "config list failed"

      case "${output}" in
         *"syntax error near unexpected token"*)
            fail "config list output contains shell parse error:
${output}"
         ;;
      esac

      case "${output}" in
         *"MULLE_SOURCETREE_CONFIG_NAME=config"*) ;;
         *)
            fail "config list output missing default config line:
${output}"
         ;;
      esac
   ) || exit 1

   log_info "----- ALL PASSED -----"

   cd ..
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SDE="${MULLE_SDE:-${PWD}/../../mulle-sde}"
}


init "$@"
main "$@"
