#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


# the tests here are wrong, mulle-craft shouldn't b
run_mulle_sde()
{
   log_fluff "####################################"
   log_fluff ${MULLE_SDE} ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################"

   exekutor "${MULLE_SDE}" ${MULLE_SDE_FLAGS} "$@"
}


expect()
{
   local expected_filename="$1"
   local filename="$2"

   local result
   local diff

   [ ! -f "${expected_filename}" ] && internal_fail "expected file missing"
   [ ! -f "${filename}" ]          && fail "Result file '${filename}' is missing"

   diff="`diff "${expected_filename}" "${filename}"`"
   case $? in
      0)
      ;;

      1)
         fail "'${expected_filename}' '${filename}':
${diff}"
      ;;

      *)
         fail "diff '${expected_filename}' ${filename}' failed"
      ;;
   esac
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@"

   MULLE_SDE_EXTENSION_PATH="${PWD}"
   export MULLE_SDE_EXTENSION_PATH

   local directory

   directory="`make_tmp_directory`" || exit 1
   directory="${directory:-/tmp/build}"

   run_mulle_sde -s init --project-name "FooBar" \
                         --project-source-dir "files" \
                         --no-post-init \
                         -d "${directory}" \
                         -e test-vendor/extra \
                         none

   [ ! -d "${directory}/.mulle" ] && fail ".mulle directory failed"

   [ ! -f "${directory}/files/file" ]       && fail "\"${directory}/files/file\" not present"
   [ -f "${directory}/files/another-file" ] && fail "\"${directory}/files/another-file}\" present, though shouldn't be"

   expect "extra.txt" "${directory}/files/file"

   log_verbose "----- #1 PASSED -----"

   (
      rexekutor cd "${directory}" &&
      run_mulle_sde -s add -e test-vendor/oneshot another-file.txt
   ) || exit 1

   expect "oneshot.txt" "${directory}/files/another-file.txt"

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "file" || exit 1

   MULLE_SDE="${MULLE_SDE:-${PWD}/../../mulle-sde}"
}


init "$@"
main "$@"

