#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sde()
{
   (
      MULLE_EXECUTABLE="${MULLE_SDE}"
      MULLE_SDE_LIBEXEC_DIR="`${MULLE_SDE} libexec-dir`"

      . "${MULLE_SDE}" ${MULLE_SDE_FLAGS} "$@"
   )
}


expect_line()
{
   local pattern="$1"
   local text="$2"

   if ! grep -q "${pattern}" <<< "${text}"
   then
      fail "Expected pattern \"${pattern}\" not found in output: ${text}"
   fi
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory
   local output

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   directory="${directory:-/tmp/build}"

   run_mulle_sde -s init -d "${directory}" -m mulle-sde/c-developer executable || fail "init failed"
   cd "${directory}" || exit 1

   run_mulle_sde -s vibecoding on || fail "vibecoding on failed"

   if output="`run_mulle_sde dependency add --nodetype symlink --address foo foo 2>&1`"
   then
      fail "dependency add unexpectedly succeeded in vibecoding mode"
   fi

   expect_line "nodetype symlink" "${output}"
   expect_line "vibecoding" "${output}"
   expect_line "MULLE_FETCH_SEARCH_PATH" "${output}"
   expect_line "symlinked automatically" "${output}"

   log_info "----- ALL PASSED -----"
   cd ..
   chmod -R u+w "${directory}" 2>/dev/null
   rmdir_safer "${directory}"
}


init()
{
   MULLE_SDE="${MULLE_SDE:-${PWD}/../../mulle-sde}"
}


init "$@"
main "$@"
